// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from '../src/app'

export type PageName = 'Dashboard' | 'Design' | 'Landing' | 'Runs' | 'Settings' | 'Setup'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Dashboard': unknown
    'Design': unknown
    'Landing': unknown
    'Runs': unknown
    'Settings': unknown
    'Setup': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
